### ISSUE TITLE
disallow redefinition of `id` public prop

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#526]
taking control of the `id` attribute is a bad practice, and I think we should probably do something about it, similar to what we do with `class ` attribute. The problem here is that when I do:

```js
export default class Foo extends Element {
    @api id;
}
```

```html
<c-foo  id={bike.id} ...
```

it already have a meaning for the consumer of `c-foo` since ids are very well defined and known in HTML. But the fact that `c-foo` implementation is redefining the behavior of the `id` attribute by defining the `id` property, it breaks that well defined contract in HTML, the `id` will not longer be added to the DOM, and if you attempt to use it in css, or query selector, or any other mechanism that uses the id, it will not work anymore.
