### ISSUE TITLE
In dev mode, public APIs extending from superclasses may throw when called

### ISSUE THREAD

**Issue by nolanlawson** [salesforce/lwc#3758]
### Description

LWC 3.4.0 seems to have introduced a regression (possibly caused by #3713) in the following case:

```js
// superclass.js
export default class extends LightningElement {
  @api
  foo() {}
}
```

```js
// subclass.js
export default class extends Superclass {
  foo() {}
}
```

(Note that the superclass has an `@api`, but the subclass _does not_.)

Before v3.4.0, a consumer of the subclass could call e.g.:

```js
elm.foo()
```

... and it would call the method correctly. In 3.4.0, however, an error is thrown:

    Uncaught TypeError: elm.foo is not a function

- [Repro in 3.4.0](https://stackblitz.com/edit/salesforce-lwc-qral4p?file=src%2Fmodules%2Fx%2Fsuperclass%2Fsuperclass.js,src%2Fmodules%2Fx%2Fapp%2Fapp.html,src%2Fmodules%2Fx%2Fsubclass%2Fsubclass.js,package.json&title=LWC%20playground) (throws error)
- [Comparison repro in 3.3.3](https://stackblitz.com/edit/salesforce-lwc-dt1dhz?file=src%2Fmain.js,src%2Fmodules%2Fx%2Fapp%2Fapp.html,src%2Fmodules%2Fx%2Fapp%2Fapp.js,src%2Fmodules%2Fx%2Fsubclass%2Fsubclass.js,rollup.config.js&title=LWC%20playground) (does not throw error)

Note that production mode is unaffected. This only affects dev mode.

**Comment by nolanlawson** [comment]
Possible solution: when determining whether a component property is `@api`-exposed or not, we can walk up the prototype chain to see if any superclasses have an `@api` attached.

I assume (?) that if any of them do, then it is considered exposed. This should probably be confirmed though. (E.g. what if the supersuperclass does not expose, the superclass does, and the subclass does not?)
